server:
  port: 8080
  servlet:
    context-path: /taetaeofficial.com
    # api response utf-8 인코딩.
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8
  error:
    include-exception: true
    include-stacktrace: never
    whitelabel.enabled: true
    path: /error/serverError

# 운영시 false 처리 할 것.
decorator.datasource.p6spy.enable-logging: true
decorator.datasource.p6spy.multiline: true

spring:
  profiles:
    active: devDB

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # jsp viewResolver 설정.
  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp

  # logging 설정.
  logging:
    level:
      org.hibernate.SQL: DEBUG


#  logging:
#    level:
#      org:
#        hibernate:
#          type:
#            desriptor:
#              sql: trace
#    com:
#      atoz_develop:
#        mybatissample:
#          repository: TRACE

  # jpa 설정.
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  # 업로도 file 용량 설정.
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

---
# dev 용 설정.
spring:
  config.activate.on-profile: devDB

  # database 설정.
  datasource:
    url: jdbc:h2:tcp://localhost/~/TaetaeMall
    username: sa
    password:
    driver-class-name: org.h2.Driver